## Import SQL query in Python

In [1]:
%env DB_HOST=localhost

env: DB_HOST=localhost

In [2]:
import os
os.environ.get('DB_HOST')

'localhost'

In [3]:
%load_ext sql

In [4]:
%env DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

env: DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

In [5]:
%env DATABASE_URL

'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [6]:
%sql $DATABASE_URL

In [7]:
%%sql 

SELECT * FROM orders LIMIT 10

 * postgresql://itversity_retail_user:***@localhost:5432/itversity_retail_db
10 rows affected.

[(1, datetime.datetime(2013, 7, 25, 0, 0), 11599, 'CLOSED'),
 (2, datetime.datetime(2013, 7, 25, 0, 0), 256, 'PENDING_PAYMENT'),
 (3, datetime.datetime(2013, 7, 25, 0, 0), 12111, 'COMPLETE'),
 (4, datetime.datetime(2013, 7, 25, 0, 0), 8827, 'CLOSED'),
 (5, datetime.datetime(2013, 7, 25, 0, 0), 11318, 'COMPLETE'),
 (6, datetime.datetime(2013, 7, 25, 0, 0), 7130, 'COMPLETE'),
 (7, datetime.datetime(2013, 7, 25, 0, 0), 4530, 'COMPLETE'),
 (8, datetime.datetime(2013, 7, 25, 0, 0), 2911, 'PROCESSING'),
 (9, datetime.datetime(2013, 7, 25, 0, 0), 5657, 'PENDING_PAYMENT'),
 (10, datetime.datetime(2013, 7, 25, 0, 0), 5648, 'PENDING_PAYMENT')]

## Validate Pandas and SQL Integration

In [8]:
import pandas as pd

In [9]:
conn_uri = 'postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db'

In [10]:
pd.read_sql('orders', conn_uri)

       order_id order_date  order_customer_id     order_status
0             1 2013-07-25              11599           CLOSED
1             2 2013-07-25                256  PENDING_PAYMENT
2             3 2013-07-25              12111         COMPLETE
3             4 2013-07-25               8827           CLOSED
4             5 2013-07-25              11318         COMPLETE
...         ...        ...                ...              ...
68878     68879 2014-07-09                778         COMPLETE
68879     68880 2014-07-13               1117         COMPLETE
68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881     68882 2014-07-22              10000          ON_HOLD
68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 4 columns]

In [11]:
query = ''' 
    SELECT order_status, count(*) AS order_count
    FROM orders
    GROUP BY 1
    ORDER BY 2 DESC
'''

In [12]:
pd.read_sql(query, conn_uri)

      order_status  order_count
0         COMPLETE        22899
1  PENDING_PAYMENT        15030
2       PROCESSING         8275
3          PENDING         7610
4           CLOSED         7556
5          ON_HOLD         3798
6  SUSPECTED_FRAUD         1558
7         CANCELED         1428
8   PAYMENT_REVIEW          729